// ============================================================
// 🏛️ COMPREHENSIVE FREE COMPETITIVE EXAM CHAPTER-WISE GUIDES & ROADMAPS
// 100% FREE OFFICIAL RESOURCES: NCERT, e-Pathshala, IGNOU, SWAYAM, NPTEL & Open YouTube Courses
// ============================================================

export const COMPETITIVE_EXAMS_DATA = [
  {
    id: "upsc-cse",
    name: "UPSC Civil Services Examination (IAS / IPS / IFS)",
    shortName: "UPSC CSE",
    badge: "🏛️ Central Civil Services",
    icon: "🏛️",
    accentColor: "#6366f1",
    tagline: "India's premier administrative examination covering Prelims (GS + CSAT), Mains & Personality Test",
    eligibility: "Graduate in any discipline • Age 21-32 years",
    totalMarks: "2025 Marks (Mains 1750 + Interview 275)",
    phases: [
      {
        phaseName: "Phase 1: Foundation (Months 1-3)",
        focus: "NCERT Textbooks & Basic Conceptual Clarity",
        milestones: [
          "Read NCERTs Class 6-12 (History, Geography, Polity, Economy, Science) via official free e-Pathshala",
          "Start daily newspaper reading (The Hindu / Indian Express editorials)",
          "Understand complete syllabus blueprint and Previous Year Questions (PYQs 2013-Present)",
          "Finalize your Optional Subject based on background and interest",
        ],
      },
      {
        phaseName: "Phase 2: Core Standard Books & Notes (Months 4-8)",
        focus: "Standard reference literature and static notes compilation",
        milestones: [
          "Indian Polity: M. Laxmikanth (Cover Constitutional Framework, Parliament, Judiciary)",
          "Modern Indian History: Spectrum (Rajiv Ahir) + Bipin Chandra + Class 12 Themes",
          "Geography: G.C. Leong + Class 11-12 NCERTs + Physical Map Work",
          "Economy: NCERT Macroeconomics + Ramesh Singh / Vivek Singh + Budget & Economic Survey",
          "Environment & Ecology: PMF IAS / Shankar IAS + Ramsar Wetlands & National Parks",
          "Art & Culture: Nitin Singhania + NCERT Class 11 Fine Arts (Free PDF)",
          "Ethics (GS 4): Lexicon + 2nd ARC Recommendations & Case Studies Frameworks",
        ],
      },
      {
        phaseName: "Phase 3: Answer Writing & Current Affairs (Months 9-11)",
        focus: "Mains Answer Writing, PYQ Solving & Current Affairs Synthesis",
        milestones: [
          "Daily 2-3 Mains Answer writing practice (Intro -> Body with Diagram -> Conclusion)",
          "Compile monthly Current Affairs magazines (VisionIAS / Insights on India open compilations)",
          "Complete Optional Subject syllabus (Paper 1 & Paper 2)",
          "Write 8 Essay full-length mock papers with multi-dimensional dimensions (PESTLE framework)",
        ],
      },
      {
        phaseName: "Phase 4: Prelims Intensive & Test Series (Months 12-14)",
        focus: "Prelims MCQs, CSAT Mastery & Revision Cycles",
        milestones: [
          "Solve 40-50 Full-length Prelims Mock Tests (Target 110+ in GS Paper 1)",
          "CSAT Paper 2: Practice Reading Comprehension, Reasoning & Quantitative Aptitude (Qualify 66+ marks)",
          "Revise 3 rounds of static subjects + 1 year Current Affairs compilation",
          "Review all UPSC Prelims PYQs from 2011 to 2025",
        ],
      },
    ],
    chapterGuides: [
      {
        subjectId: "upsc-polity",
        subjectName: "Indian Polity & Constitution",
        icon: "⚖️",
        weightage: "Prelims: 15-18 Questions • Mains: 250 Marks (GS-2)",
        freeOfficialBooks: [
          {
            name: "NCERT Class 11: Indian Constitution at Work",
            type: "Official NCERT Free PDF",
            url: "https://ncert.nic.in/textbook.php?keps1=0-10",
            description: "Foundational textbook explaining Preamble, Rights, Federalism & Constitution machinery.",
          },
          {
            name: "Indian Polity by M. Laxmikanth",
            type: "Open Library Free Access",
            url: "https://openlibrary.org/search?q=Indian+Polity+Laxmikanth",
            description: "The gold standard book for Civil Services Polity preparation.",
          },
          {
            name: "eGyanKosh Public Administration & Polity",
            type: "IGNOU Free Open Courseware",
            url: "https://egyankosh.ac.in/handle/123456789/41982",
            description: "Comprehensive public university lecture notes on Indian political systems.",
          },
        ],
        freeVideoLectures: [
          {
            title: "Complete Indian Polity Full Marathon Masterclass",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=complete+indian+polity+marathon+upsc+full+course",
            description: "Full chapter-by-chapter explanation of Laxmikanth and Constitution Articles.",
          },
          {
            title: "Important Supreme Court Judgments & Basic Structure Series",
            channel: "Legal & UPSC Lecture Series",
            url: "https://www.youtube.com/results?search_query=landmark+supreme+court+judgments+upsc+marathon",
            description: "Kesavananda Bharati, Minerva Mills, Puttaswamy and key constitutional cases.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "Historical Background & Making of the Constitution",
            importance: "🔥 High Yield",
            whatToStudy: "1. Read NCERT Class 11 (Ch 1) -> 2. Laxmikanth (Ch 1 & 2) -> 3. Focus on Regulating Act 1773 to GoI Act 1935.",
            keyTopics: [
              "Regulating Act 1773, Pitt's India Act 1784, Charter Acts 1813 & 1833",
              "Government of India Act 1919 (Dyarchy) and GoI Act 1935 (Provincial Autonomy)",
              "Constituent Assembly: Elections, Committees, Objectives Resolution & Adoption dates",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=making+of+indian+constitution+upsc+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?keps1=1-10",
            pyqFocus: "Direct questions on GoI Act 1935 features, Drafting Committee members, and Interim Government.",
          },
          {
            chapterNo: 2,
            title: "Preamble, Salient Features & Constitutional Philosophy",
            importance: "🔥 High Yield",
            whatToStudy: "1. Laxmikanth Ch 3 & 4 -> 2. Understand Berubari Case (1960), Kesavananda (1973), LIC (1995).",
            keyTopics: [
              "Keywords: Sovereign, Socialist, Secular, Democratic, Republic, Justice, Liberty, Equality, Fraternity",
              "42nd Constitutional Amendment 1976 additions (Socialist, Secular, Integrity)",
              "Whether Preamble is part of Constitution and whether it is amendable",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=preamble+of+indian+constitution+upsc+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?keps1=10-10",
            pyqFocus: "Exact definitions of 'Republic', 'Liberty of thought', and amendability under Article 368.",
          },
          {
            chapterNo: 3,
            title: "Fundamental Rights (Articles 12 to 35)",
            importance: "🔥 High Yield (2-3 Qs Every Year)",
            whatToStudy: "1. Read NCERT Class 11 Ch 2 -> 2. Laxmikanth Ch 7 thoroughly -> 3. Memorize all 6 Writs.",
            keyTopics: [
              "Article 12 (Definition of State) and Article 13 (Doctrine of Judicial Review & Eclipse)",
              "Right to Equality (Articles 14-18) & Right to Freedom (Articles 19-22)",
              "Right against Exploitation (23-24) & Freedom of Religion (25-28)",
              "Cultural & Educational Rights (29-30) & Article 32 Constitutional Remedies (Habeas Corpus, Mandamus, Quo Warranto, Certiorari, Prohibition)",
              "Article 21: Expanding horizons (Privacy, Clean Environment, Right to Education 21A)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=fundamental+rights+article+12+to+35+upsc+marathon",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?keps1=2-10",
            pyqFocus: "Subtle differences between Habeas Corpus vs Mandamus, Reasonable restrictions under Article 19(2).",
          },
          {
            chapterNo: 4,
            title: "Directive Principles (DPSP) & Fundamental Duties",
            importance: "⭐ Essential",
            whatToStudy: "1. Laxmikanth Ch 8 & 9 -> 2. Classification: Socialistic, Gandhian, Liberal-Intellectual.",
            keyTopics: [
              "Articles 36 to 51: DPSP non-justiciable character & comparison with Fundamental Rights",
              "Key Articles: 39A (Free legal aid), 40 (Village Panchayats), 44 (Uniform Civil Code), 48A (Environment), 50 (Separation of Judiciary)",
              "Fundamental Duties: Article 51A (Swaran Singh Committee, 42nd & 86th Amendments)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=dpsp+and+fundamental+duties+upsc+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?keps1=2-10",
            pyqFocus: "Minerva Mills case harmonization of Part III and Part IV; 11th Fundamental Duty (86th CAA 2002).",
          },
          {
            chapterNo: 5,
            title: "The Union Executive & Parliament (President, PM, Lok Sabha & Rajya Sabha)",
            importance: "🔥 High Yield",
            whatToStudy: "1. Laxmikanth Ch 17-23 -> 2. Compare Lok Sabha vs Rajya Sabha powers, Money Bill vs Financial Bills.",
            keyTopics: [
              "President of India: Election collegium, Impeachment (Art 61), Ordinance making power (Art 123), Pardoning power (Art 72)",
              "Prime Minister & Council of Ministers: Collective responsibility (Art 75)",
              "Parliamentary Procedures: Question Hour, Zero Hour, Calling Attention, Adjournment Motion",
              "Legislative Process: Ordinary Bill, Money Bill (Art 110), Financial Bills (Art 117), Joint Sitting (Art 108)",
              "Parliamentary Committees: Public Accounts Committee (PAC), Estimates Committee, Committee on Public Undertakings (COPU)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=indian+parliament+upsc+laxmikanth+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?keps1=5-10",
            pyqFocus: "Ordinance validity duration, Rajya Sabha special powers (Art 249, Art 312), PAC composition.",
          },
          {
            chapterNo: 6,
            title: "The Judiciary (Supreme Court, High Courts & Judicial Review)",
            importance: "🔥 High Yield",
            whatToStudy: "1. Laxmikanth Ch 26 & 33 -> 2. Collegium System, Judicial Activism vs Judicial Overreach, Contempt of Court.",
            keyTopics: [
              "Supreme Court Jurisdiction: Original (Art 131), Appellate, Advisory (Art 143), Writ (Art 32)",
              "Appointment of Judges: NJAC 99th Amendment striking down, 1st/2nd/3rd Judges Cases",
              "High Courts: Writ Jurisdiction under Art 226 (broader than SC Art 32), Subordinate Courts",
              "Doctrine of Basic Structure & Judicial Review evolution",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=supreme+court+of+india+upsc+judiciary+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?keps1=6-10",
            pyqFocus: "Article 142 (Complete Justice), Court of Record (Art 129), Collegium mechanism.",
          },
        ],
      },
      {
        subjectId: "upsc-modern-history",
        subjectName: "Modern Indian History & Freedom Struggle",
        icon: "📜",
        weightage: "Prelims: 8-12 Questions • Mains: GS-1 (75-100 Marks)",
        freeOfficialBooks: [
          {
            name: "NCERT Class 12: Themes in Indian History (Part III)",
            type: "Official NCERT Free PDF",
            url: "https://ncert.nic.in/textbook.php?lehs3=0-6",
            description: "Official NCERT text on Colonialism, Countryside, 1857 Revolt & Mahatma Gandhi.",
          },
          {
            name: "A Brief History of Modern India (Spectrum)",
            type: "Open Library Public Access",
            url: "https://openlibrary.org/search?q=Spectrum+Modern+India+Rajiv+Ahir",
            description: "Chronological guide to modern Indian history and British policies.",
          },
          {
            name: "India's Struggle for Independence by Bipin Chandra",
            type: "Public University Repository",
            url: "https://openlibrary.org/search?q=Bipin+Chandra+Indias+Struggle+for+Independence",
            description: "Deep narrative on the socio-economic and political dynamics of Indian freedom fighters.",
          },
        ],
        freeVideoLectures: [
          {
            title: "Modern Indian History Complete UPSC Masterclass",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=complete+modern+indian+history+upsc+marathon+full+course",
            description: "Comprehensive lecture series covering 1757 to 1947 with maps and timelines.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "Advent of Europeans & British Consolidation in India (1757-1856)",
            importance: "⭐ Essential",
            whatToStudy: "1. Spectrum Ch 2-5 -> 2. Battle of Plassey 1757, Buxar 1764, Subsidiary Alliance, Doctrine of Lapse.",
            keyTopics: [
              "Portuguese, Dutch, French vs British Rivalry & Carnatic Wars",
              "Battle of Plassey (1757) and Battle of Buxar (1764) Treaty of Allahabad",
              "Anglo-Mysore Wars (Hyder Ali & Tipu Sultan), Anglo-Maratha Wars, Anglo-Sikh Wars",
              "Lord Wellesley's Subsidiary Alliance & Lord Dalhousie's Doctrine of Lapse (Satara, Sambalpur, Jhansi, Awadh annexation)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=advent+of+europeans+in+india+upsc+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?lehs3=1-6",
            pyqFocus: "Dual Government of Bengal (Robert Clive), Subsidiary Alliance terms, Treaty of Salbai & Bassein.",
          },
          {
            chapterNo: 2,
            title: "The Revolt of 1857 & Early Peasant / Tribal Uprisings",
            importance: "🔥 High Yield",
            whatToStudy: "1. NCERT Class 12 Theme 11 -> 2. Spectrum Ch 6-7 -> 3. Leaders and centers of revolt.",
            keyTopics: [
              "Causes: Political (annexation), Socio-Religious (Lex Loci Act, Enfield cartridge), Economic (ruin of handicrafts)",
              "Key Leaders & Centers: Delhi (Bakht Khan), Kanpur (Nana Saheb), Lucknow (Begum Hazrat Mahal), Bihar (Kunwar Singh), Faizabad (Maulvi Ahmadullah)",
              "Government of India Act 1858: Queen's Proclamation, Abolition of Company Rule, Secretary of State & Viceroy",
              "Early Tribal/Peasant Revolts: Santhal Rebellion (1855-56 Sidhu & Kanhu), Indigo Revolt (1859-60), Birsa Munda Ulgulan (1899-1900)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=revolt+of+1857+upsc+modern+history+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?lehs3=2-6",
            pyqFocus: "Tribal uprising leaders, causes of 1857 failure, Army reorganization under Peel Commission.",
          },
          {
            chapterNo: 3,
            title: "Socio-Religious Reform Movements (19th & 20th Century)",
            importance: "🔥 High Yield",
            whatToStudy: "1. Spectrum Ch 8-9 -> 2. Create comparative chart: Founder, Year, Organization, Key reforms, Journals.",
            keyTopics: [
              "Brahmo Samaj (Raja Ram Mohan Roy, Debendranath Tagore, Keshab Chandra Sen) & Atmiya Sabha",
              "Arya Samaj (Swami Dayanand Saraswati - Shuddhi movement, 'Go back to Vedas')",
              "Ramakrishna Mission (Swami Vivekananda - Chicago Speech 1893, Neo-Vedanta)",
              "Satyashodhak Samaj (Jyotirao Phule - Gulamgiri, education for women & lower castes)",
              "Aligarh Movement (Sir Syed Ahmad Khan), Theosophical Society (Annie Besant), Young Bengal (Henry Vivian Derozio)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=socio+religious+reform+movements+upsc+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?lehs3=3-6",
            pyqFocus: "Newspapers/journals founded by reformers (e.g. Sambad Kaumudi, Mirat-ul-Akbar, Satyarth Prakash).",
          },
          {
            chapterNo: 4,
            title: "Gandhian Era & Mass Movements (1915-1947)",
            importance: "🔥 High Yield (Core Focus)",
            whatToStudy: "1. NCERT Class 12 Theme 13 -> 2. Spectrum Ch 15-24 -> 3. Sequence: Champaran -> Kheda -> NCM -> CDM -> QIM.",
            keyTopics: [
              "Early Satyagrahas: Champaran (1917 Tinkathia system), Ahmedabad Mill Strike (1918 1st Hunger Strike), Kheda (1918 1st Non-Cooperation)",
              "Rowlatt Act & Jallianwala Bagh Massacre (1919) -> Non-Cooperation & Khilafat Movement (1920-22) -> Chauri Chaura incident",
              "Swarajists vs No-Changers (CR Das, Motilal Nehru), Simon Commission & Nehru Report (1928), Lahore Session 'Poorna Swaraj' (1929)",
              "Civil Disobedience Movement (1930 Dandi March), Gandhi-Irwin Pact (1931), Poona Pact (1932 Gandhi & Ambedkar)",
              "Quit India Movement (1942 'Do or Die'), INA & Subhas Chandra Bose, Cabinet Mission Plan (1946) & Mountbatten Plan (1947)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=gandhian+era+freedom+struggle+upsc+marathon",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?lehs3=4-6",
            pyqFocus: "Individual Satyagraha, August Offer 1940, Cripps Mission proposals, Desai-Liaquat Pact.",
          },
        ],
      },
      {
        subjectId: "upsc-geography",
        subjectName: "Physical & Indian Geography",
        icon: "🌍",
        weightage: "Prelims: 10-14 Questions • Mains: GS-1 (100 Marks)",
        freeOfficialBooks: [
          {
            name: "NCERT Class 11: Fundamentals of Physical Geography",
            type: "Official NCERT Free PDF",
            url: "https://ncert.nic.in/textbook.php?kegy2=0-16",
            description: "The primary source for Geomorphology, Climatology, and Oceanography concepts.",
          },
          {
            name: "NCERT Class 11: India - Physical Environment",
            type: "Official NCERT Free PDF",
            url: "https://ncert.nic.in/textbook.php?kegy1=0-7",
            description: "Complete guide to Indian physiography, river drainage systems, and monsoons.",
          },
          {
            name: "Certificate Physical & Human Geography by G.C. Leong",
            type: "Open Library Free Access",
            url: "https://openlibrary.org/search?q=Certificate+Physical+Geography+GC+Leong",
            description: "World climatic regions, landforms, and meteorological processes.",
          },
        ],
        freeVideoLectures: [
          {
            title: "Physical Geography & Indian Mapwork Masterclass",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=physical+geography+upsc+ncert+marathon+full+course",
            description: "Detailed animations for Plate Tectonics, Monsoon mechanisms, and Ocean Currents.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "Geomorphology: Earth Interior, Plate Tectonics & Landforms",
            importance: "🔥 High Yield",
            whatToStudy: "1. NCERT Class 11 Physical Geo Ch 2-7 -> 2. Understand P & S Waves, Continental Drift Theory (Wegener).",
            keyTopics: [
              "Structure of Earth: Crust, Mantle (Asthenosphere), Core (Gutenberg & Mohorovicic discontinuities)",
              "Plate Tectonics Theory: Convergent, Divergent & Transform boundaries (Ring of Fire)",
              "Volcanoes & Earthquakes: Shadow zones, Caldera, Shield vs Composite volcanoes",
              "Fluvial, Aeolian, Glacial & Karst Landforms (Erosional vs Depositional)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=geomorphology+plate+tectonics+upsc+geography",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?kegy2=4-16",
            pyqFocus: "P-wave and S-wave shadow zones, Karst topography (Stalagmites/Stalactites), Cirque/Moraine formations.",
          },
          {
            chapterNo: 2,
            title: "Climatology: Atmospheric Circulation, Pressure Belts & Cyclones",
            importance: "🔥 High Yield",
            whatToStudy: "1. NCERT Class 11 Ch 8-12 -> 2. Master Coriolis force, Hadley/Ferrel/Polar Cells, Tropical vs Temperate Cyclones.",
            keyTopics: [
              "Structure of Atmosphere: Troposphere, Stratosphere (Ozone), Mesosphere, Thermosphere (Ionosphere)",
              "Heat Budget of the Earth & Temperature Inversion conditions",
              "Planetary Winds: Trade Winds, Westerlies, Polar Easterlies & ITCZ seasonal shift",
              "Tropical Cyclones: Formation conditions (Coriolis force, 27°C sea surface temp, low vertical wind shear)",
              "Jet Streams & Western Disturbances impact on Indian Winter rainfall",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=climatology+atmosphere+cyclones+upsc+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?kegy2=9-16",
            pyqFocus: "Conditions for Temperature Inversion, Tropical Cyclone eye structure, Jet Stream meandering.",
          },
          {
            chapterNo: 3,
            title: "Indian Physiography & River Drainage Systems",
            importance: "🔥 High Yield (Mapwork Focus)",
            whatToStudy: "1. NCERT Class 11 India Physical Ch 1-3 -> 2. Draw river basin sketches with Left/Right bank tributaries.",
            keyTopics: [
              "Himalayan Ranges: Trans-Himalayas (Karakoram, Ladakh, Zaskar), Greater Himalayas (Himadri), Middle (Himachal), Outer (Shiwalik)",
              "Peninsular Plateau: Western Ghats (Passes: Thal, Bhor, Palghat) vs Eastern Ghats",
              "Indus River System: Jhelum, Chenab, Ravi, Beas, Sutlej (Indus Waters Treaty)",
              "Ganga-Brahmaputra System: Alaknanda-Bhagirathi (Devprayag), Yamuna, Ghaghara, Kosi, Teesta, Dihang",
              "Peninsular Rivers: East-flowing (Godavari, Krishna, Cauvery, Mahanadi) vs West-flowing (Narmada, Tapti rift valleys)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=indian+river+system+mapwork+upsc+geography",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?kegy1=3-7",
            pyqFocus: "Exact north-to-south ordering of tributaries, National Parks situated on river basins.",
          },
          {
            chapterNo: 4,
            title: "Indian Monsoons, El Niño, La Niña & IOD",
            importance: "🔥 High Yield",
            whatToStudy: "1. NCERT Class 11 India Physical Ch 4 -> 2. Mechanism: Somali Jet, Mascarene High, Tibetan Heating.",
            keyTopics: [
              "Classical thermal concept vs Modern dynamic concept (Jet stream theory)",
              "South-West Monsoon branches: Arabian Sea branch vs Bay of Bengal branch",
              "El Niño-Southern Oscillation (ENSO), Walker Circulation & La Niña cooling effect",
              "Indian Ocean Dipole (Positive IOD vs Negative IOD) & Madden-Julian Oscillation (MJO)",
              "Retreating Monsoon & North-East Monsoon rainfall in Tamil Nadu coast (Coromandel Coast)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=indian+monsoon+el+nino+la+nina+upsc+geography",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?kegy1=4-7",
            pyqFocus: "Impact of Positive IOD on Indian monsoon, Break in monsoon causes.",
          },
        ],
      },
      {
        subjectId: "upsc-economy",
        subjectName: "Indian Economy & Macroeconomics",
        icon: "📈",
        weightage: "Prelims: 15-20 Questions • Mains: GS-3 (125 Marks)",
        freeOfficialBooks: [
          {
            name: "NCERT Class 12: Introductory Macroeconomics",
            type: "Official NCERT Free PDF",
            url: "https://ncert.nic.in/textbook.php?leec1=0-6",
            description: "Core conceptual clarity on GDP, National Income, Money Supply, and Balance of Payments.",
          },
          {
            name: "Union Budget & Economic Survey (Official Ministry of Finance)",
            type: "Official Govt Free Portal",
            url: "https://www.indiabudget.gov.in/",
            description: "Direct official budget documents, macroeconomic trends, and socio-economic schemes.",
          },
          {
            name: "Indian Economy by Ramesh Singh",
            type: "Open Library Free Access",
            url: "https://openlibrary.org/search?q=Indian+Economy+Ramesh+Singh",
            description: "Standard Civil Services reference textbook covering five-year plans to GST.",
          },
        ],
        freeVideoLectures: [
          {
            title: "Complete Indian Economy & Macroeconomics Masterclass",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=complete+indian+economy+upsc+macroeconomics+marathon",
            description: "Comprehensive coverage of RBI Monetary Policy, Inflation, Banking, and BoP.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "National Income Accounting & Growth Metrics",
            importance: "🔥 High Yield",
            whatToStudy: "1. NCERT Macroeconomics Ch 1-2 -> 2. GDP, GNP, NNP, Factor Cost vs Market Price, GVA.",
            keyTopics: [
              "Gross Domestic Product (GDP) vs Gross National Product (GNP) calculation methods",
              "Nominal GDP vs Real GDP (GDP Deflator formula)",
              "Gross Value Added (GVA) at Basic Prices vs Market Prices",
              "Purchasing Power Parity (PPP) & Capital Output Ratio (ICOR)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=national+income+gdp+gnp+upsc+economy",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?leec1=2-6",
            pyqFocus: "Calculation of Real vs Nominal GDP, GVA calculation under 2015 base year methodology.",
          },
          {
            chapterNo: 2,
            title: "Monetary Policy, RBI Operations & Money Supply",
            importance: "🔥 High Yield (Every Year 3-4 Qs)",
            whatToStudy: "1. NCERT Macroeconomics Ch 3 -> 2. Quantitative tools: Repo, Reverse Repo, SDF, MSF, CRR, SLR, OMO.",
            keyTopics: [
              "Money Aggregates: Reserve Money (M0), Narrow Money (M1), Broad Money (M3), Money Multiplier",
              "RBI Monetary Policy Committee (MPC): 4% +/- 2% CPI Inflation Targeting framework",
              "Liquidity Adjustment Facility (LAF): Repo Rate, Standing Deposit Facility (SDF), Marginal Standing Facility (MSF)",
              "Open Market Operations (OMO), Operation Twist, Long Term Repo Operations (LTRO)",
              "Non-Performing Assets (NPAs): Gross NPA vs Net NPA, IBC 2016, Bad Bank (NARCL-IDRCL)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=rbi+monetary+policy+instruments+upsc+economy",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?leec1=3-6",
            pyqFocus: "Money Multiplier determinants, effect of Cash Reserve Ratio increase on money supply.",
          },
          {
            chapterNo: 3,
            title: "Fiscal Policy, Government Budgeting & Taxation (GST)",
            importance: "🔥 High Yield",
            whatToStudy: "1. NCERT Macroeconomics Ch 5 -> 2. Revenue vs Capital Account, Fiscal Deficit, Primary Deficit, FRBM Act.",
            keyTopics: [
              "Structure of Budget: Revenue Receipts (Tax & Non-Tax) vs Capital Receipts (Disinvestment, Borrowings)",
              "Revenue Expenditure vs Capital Expenditure (Productive asset creation)",
              "Deficits: Fiscal Deficit, Revenue Deficit, Effective Revenue Deficit, Primary Deficit",
              "Goods and Services Tax (GST): GST Council (Art 279A), Dual GST model, Input Tax Credit (ITC)",
              "FRBM Act 2003 targets & NK Singh Committee recommendations",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=government+budgeting+fiscal+deficit+gst+upsc+economy",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?leec1=5-6",
            pyqFocus: "Components included in Capital Receipts vs Revenue Receipts, Primary Deficit formula.",
          },
          {
            chapterNo: 4,
            title: "Balance of Payments (BoP), Forex Reserves & International Trade",
            importance: "🔥 High Yield",
            whatToStudy: "1. NCERT Macroeconomics Ch 6 -> 2. Current Account vs Capital Account, FDI vs FPI, NEER/REER.",
            keyTopics: [
              "Current Account: Merchandise Trade balance + Invisibles (Services, Transfers, Income)",
              "Capital Account: Foreign Direct Investment (FDI), Foreign Portfolio Investment (FPI), External Commercial Borrowings (ECB)",
              "Current Account Deficit (CAD) vs Fiscal Deficit (Twin Deficit Problem)",
              "Foreign Exchange Reserves: Foreign Currency Assets, Gold, SDRs (IMF), Reserve Tranche Position (RTP)",
              "Exchange Rate Regimes: Managed Floating, Nominal Effective Exchange Rate (NEER) vs Real Effective Exchange Rate (REER)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=balance+of+payments+bop+fdi+fpi+upsc+economy",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?leec1=6-6",
            pyqFocus: "Difference between FDI vs FPI, Components of Forex reserves in India.",
          },
        ],
      },
    ],
    recommendedBooks: [
      { subject: "Polity", book: "Indian Polity by M. Laxmikanth (7th Edition)", freeLink: "https://openlibrary.org/search?q=Indian+Polity+Laxmikanth" },
      { subject: "Modern History", book: "A Brief History of Modern India (Spectrum) by Rajiv Ahir", freeLink: "https://openlibrary.org/search?q=Spectrum+Modern+India" },
      { subject: "Geography", book: "Certificate Physical and Human Geography by G.C. Leong + NCERT Class 11", freeLink: "https://openlibrary.org/search?q=Physical+Geography+GC+Leong" },
      { subject: "Economy", book: "Indian Economy by Ramesh Singh + Union Budget", freeLink: "https://openlibrary.org/search?q=Indian+Economy+Ramesh+Singh" },
      { subject: "Environment", book: "Environment by Shankar IAS Academy / PMF IAS", freeLink: "https://openlibrary.org/search?q=Environment+Ecology" },
      { subject: "Art & Culture", book: "Indian Art and Culture by Nitin Singhania + NCERT Fine Arts", freeLink: "https://openlibrary.org/search?q=Indian+Art+and+Culture" },
    ],
    syllabus: [
      {
        subject: "General Studies Paper 1 (Indian Heritage, History, Geography & Society)",
        weight: "250 Marks",
        topics: [
          "Indian Art Forms, Literature and Architecture from ancient to modern times",
          "Modern Indian History from mid-18th century until present (Significant events & personalities)",
          "The Freedom Struggle — its various stages and important contributors",
          "Post-independence consolidation and reorganization within the country",
          "History of the World (Industrial revolution, world wars, redrawal of national boundaries)",
          "Salient features of Indian Society, Diversity of India & Role of women",
          "Effects of Globalization on Indian society, Social empowerment, communalism, regionalism",
          "Salient features of World's Physical Geography & Distribution of key natural resources",
          "Important Geophysical phenomena (Earthquakes, Tsunami, Volcanic activity, Cyclone)",
        ],
      },
      {
        subject: "General Studies Paper 2 (Governance, Constitution, Polity & IR)",
        weight: "250 Marks",
        topics: [
          "Indian Constitution — Historical underpinnings, evolution, features, amendments, basic structure",
          "Functions and responsibilities of the Union and the States, issues pertaining to federal structure",
          "Separation of powers between various organs, dispute redressal mechanisms and institutions",
          "Comparison of the Indian constitutional scheme with that of other countries",
          "Parliament and State Legislatures — structure, functioning, conduct of business, powers & privileges",
          "Salient features of the Representation of People's Act",
          "Statutory, regulatory and various quasi-judicial bodies",
          "Welfare schemes for vulnerable sections & Performance of these schemes",
          "Important aspects of governance, transparency and accountability, e-governance",
          "India and its neighborhood relations & Bilateral, regional and global groupings involving India",
        ],
      },
      {
        subject: "General Studies Paper 3 (Technology, Economic Development, Biodiversity & Security)",
        weight: "250 Marks",
        topics: [
          "Indian Economy and issues relating to planning, mobilization of resources, growth and employment",
          "Inclusive growth and issues arising from it, Government Budgeting",
          "Major crops, cropping patterns, types of irrigation and irrigation systems",
          "Issues related to direct and indirect farm subsidies and minimum support prices (MSP), PDS",
          "Food processing and related industries in India — scope and significance",
          "Land reforms in India & Effects of liberalization on the economy",
          "Infrastructure: Energy, Ports, Roads, Airports, Railways",
          "Science and Technology — developments and their applications in everyday life",
          "Achievements of Indians in science & technology; indigenization of technology",
          "Awareness in IT, Space, Computers, Robotics, Nanotechnology, Bio-technology and IPR",
          "Conservation, environmental pollution and degradation, environmental impact assessment",
          "Disaster management & Linkages between development and spread of extremism",
          "Role of external state and non-state actors in creating challenges to internal security",
          "Challenges to internal security through communication networks, role of media & cyber security",
        ],
      },
      {
        subject: "General Studies Paper 4 (Ethics, Integrity & Aptitude)",
        weight: "250 Marks",
        topics: [
          "Ethics and Human Interface: Essence, determinants and consequences of Ethics in-human actions",
          "Human Values — lessons from the lives and teachings of great leaders, reformers and administrators",
          "Attitude: content, structure, function; its influence and relation with thought and behaviour",
          "Aptitude and foundational values for Civil Service: integrity, impartiality, empathy & compassion",
          "Emotional Intelligence — concepts, and their utilities and application in administration",
          "Contributions of moral thinkers and philosophers from India and world",
          "Public/Civil service values and Ethics in Public administration: status and problems",
          "Probity in Governance: Concept of public service, Philosophical basis of governance and probity",
          "Case Studies on above issues (Practical situational dilemmas in district administration)",
        ],
      },
    ],
  },

  {
    id: "ssc-cgl",
    name: "SSC CGL / CHSL / CPO (Staff Selection Commission)",
    shortName: "SSC CGL & CHSL",
    badge: "⚡ Staff Selection Commission",
    icon: "⚡",
    accentColor: "#10b981",
    tagline: "Combined Graduate Level Examination for Group B & C Central Government Posts across Ministries",
    eligibility: "Bachelor's Degree • Age 18-32 years",
    totalMarks: "Tier-1 (200 Marks Qualifying) + Tier-2 (390 Marks Merit)",
    phases: [
      {
        phaseName: "Phase 1: Foundation & Speed Calculation (Weeks 1-6)",
        focus: "Quantitative Speed Math, Grammar Rules & Logical Reasoning Concepts",
        milestones: [
          "Master Mental Math: Squares (1-50), Cubes (1-30), Fraction-to-Percentage tables, Multiplication tricks",
          "Quantitative Aptitude: Complete Percentage, Profit & Loss, Ratio & Proportion, Time & Work, SI/CI",
          "English Grammar: 120 Rules of Grammar (Subject-Verb Agreement, Tenses, Prepositions, Voices & Narration)",
          "Reasoning: Syllogisms, Coding-Decoding, Blood Relations, Number Series, Analogy, Matrix",
        ],
      },
      {
        phaseName: "Phase 2: Advanced Math & Static General Awareness (Weeks 7-14)",
        focus: "Geometry, Mensuration, Algebra, Trigonometry & Static GK",
        milestones: [
          "Advanced Math: Algebra identities, Geometry circles/triangles theorems, Trigonometry heights & distances",
          "Static GK: Ancient/Medieval/Modern History, Articles & Amendments of Constitution, River systems, Dance/Festivals",
          "General Science: Physics Laws, Chemistry Periodic Table & Everyday Compounds, Biology Human Body systems",
          "Vocabulary: 1000 One-Word Substitutions, 1000 Idioms & Phrases, 500 Confusing Words",
        ],
      },
      {
        phaseName: "Phase 3: Computer Knowledge & Module Speed Drills (Weeks 15-20)",
        focus: "Tier-2 Computer Proficiency, Data Entry Speed & Typing Practice",
        milestones: [
          "Computer Knowledge Module: Basics of CPU, Memory, MS Office (Word/Excel/PowerPoint shortcuts), Networking & Cyber Security",
          "Typing Test: Practice daily 15-minute typing session (Target 30+ Words Per Minute with 95% accuracy)",
          "Sectional Speed Drills: 25 questions in 15 minutes for Reasoning and Quantitative Aptitude",
        ],
      },
      {
        phaseName: "Phase 4: Full Length Mocks & Error Analysis (Weeks 21-26)",
        focus: "60+ Full Tier-1 & Tier-2 Mock Tests with Deep Weakness Analysis",
        milestones: [
          "Solve 1 full-length mock test every alternate day with timed interface",
          "Maintain an 'Error Notebook' documenting every calculation mistake and forgotten formula",
          "Solve all SSC CGL/CHSL PYQs from 2018 to 2025 (TCS Exam Pattern)",
          "Current Affairs Revision: Past 8 months Sports, Awards, Appointments, Government Schemes",
        ],
      },
    ],
    chapterGuides: [
      {
        subjectId: "ssc-quant",
        subjectName: "Quantitative Aptitude (Arithmetic & Advance Math)",
        icon: "📐",
        weightage: "Tier-1: 25 Qs (50 Marks) • Tier-2: 30 Qs (90 Marks)",
        freeOfficialBooks: [
          {
            name: "Quantitative Aptitude by R.S. Aggarwal",
            type: "Open Library Free Access",
            url: "https://openlibrary.org/search?q=Quantitative+Aptitude+RS+Aggarwal",
            description: "Universal reference practice book for arithmetic and speed calculations.",
          },
          {
            name: "NCERT Class 9 & 10 Mathematics (Geometry & Algebra)",
            type: "Official NCERT Free PDF",
            url: "https://ncert.nic.in/textbook.php?jemh1=0-15",
            description: "Official NCERT math text covering Circles, Triangles, Trigonometry & Coordinate Geometry.",
          },
        ],
        freeVideoLectures: [
          {
            title: "Complete Quantitative Aptitude for SSC CGL (Full Marathon Course)",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=complete+quantitative+aptitude+ssc+cgl+full+marathon",
            description: "Full topic-by-topic short tricks, formulas, and TCS previous year questions.",
          },
          {
            title: "Complete Advance Math (Geometry + Algebra + Trigonometry)",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=advance+maths+ssc+cgl+geometry+trigonometry+marathon",
            description: "In-depth theorem proofs and 2-second shortcut methods for high-tier exams.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "Percentages, Ratio & Proportion, Profit & Loss",
            importance: "🔥 High Yield (Arithmetic Backbone)",
            whatToStudy: "1. Memorize 1/2 to 1/20 fraction values -> 2. Successive percentage change formula -> 3. Marked price vs Discount.",
            keyTopics: [
              "Fraction to percentage conversion (1/7 = 14.28%, 1/8 = 12.5%, 1/12 = 8.33%)",
              "Profit, Loss, Marked Price (MP), Discount % & Dishonest Shopkeeper false weight tricks",
              "Ratio & Proportion, Mean Proportional, Third/Fourth Proportional, Compounded Ratio",
              "Partnership calculations (Capital x Time = Profit share ratio)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=percentage+profit+and+loss+ssc+cgl+marathon",
            freeReadingUrl: "https://openlibrary.org/search?q=Quantitative+Aptitude",
            pyqFocus: "Dishonest dealer questions, Two successive discounts of x% and y% equivalent single discount.",
          },
          {
            chapterNo: 2,
            title: "Time & Work, Pipes & Cisterns, Speed Time Distance",
            importance: "🔥 High Yield",
            whatToStudy: "1. LCM Efficiency Method -> 2. Alternate days working problems -> 3. Relative Speed (Trains & Boats).",
            keyTopics: [
              "Work = Efficiency x Time; LCM method to determine unit work per day",
              "Pipes and Cisterns (Inlet positive work, Outlet negative work efficiency)",
              "Speed = Distance / Time; Conversion km/h to m/s (multiply by 5/18)",
              "Trains: Crossing a pole/man (length of train) vs platform (length of train + platform)",
              "Boats and Streams: Downstream speed (u + v) vs Upstream speed (u - v)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=time+and+work+speed+time+distance+ssc+cgl+lecture",
            freeReadingUrl: "https://openlibrary.org/search?q=Fast+Track+Arithmetic",
            pyqFocus: "Men, women and children efficiency equivalence (M1 D1 H1 / W1 = M2 D2 H2 / W2).",
          },
          {
            chapterNo: 3,
            title: "Algebra & Linear Equations",
            importance: "🔥 High Yield (Advance Math)",
            whatToStudy: "1. Standard identities (x + 1/x = k formulas) -> 2. Symmetric value-putting method.",
            keyTopics: [
              "If x + 1/x = k, then x² + 1/x² = k² - 2; x³ + 1/x³ = k³ - 3k",
              "If x + 1/x = 1, then x³ = -1; If x + 1/x = √3, then x⁶ = -1",
              "Identity: a³ + b³ + c³ - 3abc = (a + b + c)(a² + b² + c² - ab - bc - ca)",
              "If a + b + c = 0, then a³ + b³ + c³ = 3abc",
              "Value-putting techniques to verify identities in under 15 seconds",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=algebra+ssc+cgl+short+tricks+marathon",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?jemh1=2-15",
            pyqFocus: "Direct questions on a³ + b³ + c³ when a + b + c = 0.",
          },
          {
            chapterNo: 4,
            title: "Geometry & Mensuration (Triangles, Circles & 3D Solids)",
            importance: "🔥 High Yield (Most Questions in Tier-2)",
            whatToStudy: "1. NCERT Class 9/10 Geometry -> 2. Circle Chord & Tangent theorems -> 3. Incenter, Circumcenter, Centroid.",
            keyTopics: [
              "Triangles: Incenter (Angle bisector, angle = 90 + A/2), Circumcenter (Perpendicular bisector, angle = 2A), Orthocenter, Centroid (2:1 ratio)",
              "Circles: Tangent-Secant Theorem (PT² = PA x PB), Alternate Segment Theorem, Direct Common Tangent (DCT) formula",
              "Mensuration 2D & 3D: Prism, Pyramid, Cone, Frustum, Cylinder, Sphere, Hemisphere formulas",
              "Volume comparison and melting/recasting solid geometry problems",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=geometry+and+mensuration+ssc+cgl+full+course",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?jemh1=6-15",
            pyqFocus: "Direct Common Tangent length √(d² - (r1 - r2)²), Inradius of right angle triangle (P + B - H)/2.",
          },
          {
            chapterNo: 5,
            title: "Trigonometry & Heights and Distances",
            importance: "🔥 High Yield",
            whatToStudy: "1. Values table 0°, 30°, 45°, 60°, 90° -> 2. sin²θ + cos²θ = 1 -> 3. Angle of elevation & depression ratios.",
            keyTopics: [
              "Trigonometric Ratios & Complementary Angles (sin(90-θ) = cos θ, tan(90-θ) = cot θ)",
              "Identities: sec²θ - tan²θ = 1 (sec θ + tan θ = 1 / (sec θ - tan θ)), cosec²θ - cot²θ = 1",
              "Maximum and Minimum values of a sin θ + b cos θ (Range: -√(a²+b²) to +√(a²+b²))",
              "Heights and Distances: Standard triangle ratios (30°-60°-90° is 1:√3:2, 45°-45°-90° is 1:1:√2)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=trigonometry+ssc+cgl+tricks+marathon",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?jemh1=8-15",
            pyqFocus: "Heights and distances with two complementary angles (Height = √(a * b)).",
          },
        ],
      },
      {
        subjectId: "ssc-english",
        subjectName: "English Language & Comprehension",
        icon: "📖",
        weightage: "Tier-1: 25 Qs (50 Marks) • Tier-2: 45 Qs (135 Marks - Highest Weightage)",
        freeOfficialBooks: [
          {
            name: "Objective General English by S.P. Bakshi",
            type: "Open Library Free Access",
            url: "https://openlibrary.org/search?q=Objective+General+English+Bakshi",
            description: "Standard grammar rules, error spotting, voice, and vocabulary compilation.",
          },
          {
            name: "Plinth to Paramount English by Neetu Singh",
            type: "Public Educational Repository",
            url: "https://openlibrary.org/search?q=General+English+Grammar",
            description: "Bilingual rule-by-rule explanation with previous year TCS question sets.",
          },
        ],
        freeVideoLectures: [
          {
            title: "120 Rules of English Grammar Marathon for SSC CGL",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=120+rules+of+english+grammar+ssc+cgl+marathon",
            description: "Complete error spotting rules, subject-verb agreement, and conjunctions.",
          },
          {
            title: "Top 1000 One-Word Substitutions & Idioms Root Words Masterclass",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=one+word+substitution+idioms+ssc+cgl+marathon",
            description: "Etymology, root words (e.g. -cide, -phobia, -phil, bene-, mal-), and mnemonic memory techniques.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "Subject-Verb Agreement & Syntax Rules",
            importance: "🔥 High Yield",
            whatToStudy: "1. Neither...nor, Either...or proximity rules -> 2. Collective nouns singular vs plural -> 3. 'As well as / Along with' rules.",
            keyTopics: [
              "When two subjects are joined by 'as well as', 'along with', 'together with', verb follows the FIRST subject",
              "When joined by 'either...or', 'neither...nor', 'not only...but also', verb follows the NEAREST subject",
              "Expressions like 'A number of' (plural verb) vs 'The number of' (singular verb)",
              "Indefinite pronouns: 'Each', 'Every', 'Everyone', 'Neither of', 'Either of' take singular verbs and pronouns",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=subject+verb+agreement+rules+ssc+cgl+lecture",
            freeReadingUrl: "https://openlibrary.org/search?q=General+English+Grammar",
            pyqFocus: "'One of the + plural noun + who/which + PLURAL verb' exceptions.",
          },
          {
            chapterNo: 2,
            title: "Active & Passive Voice & Direct/Indirect Narration",
            importance: "🔥 High Yield (20+ Marks in Tier-2)",
            whatToStudy: "1. Tense transformation table -> 2. Interrogative and Imperative voice rules -> 3. Universal truths in narration.",
            keyTopics: [
              "Active to Passive rules: Simple Present (is/am/are + V3), Present Continuous (is/am/are + being + V3)",
              "Modal verbs: can/could/may/must -> can be/could be + V3",
              "Imperative Sentences: 'Let + Object + be + V3' or 'You are requested/ordered to + V1'",
              "Direct to Indirect Narration: Reporting verb changes (said to -> told), Tense changes (Present -> Past, Past Simple -> Past Perfect)",
              "No change in tense for Universal Truths, Historical Facts, or Proverbial sayings",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=active+passive+voice+direct+indirect+speech+ssc+cgl+marathon",
            freeReadingUrl: "https://openlibrary.org/search?q=Objective+General+English",
            pyqFocus: "Direct speech questions starting with 'Wh-' words vs Auxiliaries ('if/whether').",
          },
          {
            chapterNo: 3,
            title: "Vocabulary, Idioms, Phrases & One-Word Substitutions",
            importance: "🔥 High Yield",
            whatToStudy: "1. Root words system -> 2. Previous 5 years TCS questions -> 3. Daily 20 idioms flashcards.",
            keyTopics: [
              "High-Frequency Idioms: 'Bite the bullet', 'At the eleventh hour', 'A blessing in disguise', 'Burn the midnight oil'",
              "Root Words: Chron (Time), Pathy (Feeling), Morph (Form), Omni (All), Somn (Sleep), Loqu/Loc (Talk)",
              "One-Word Substitutions: Philanthropist, Misogynist, Polyglot, Altruist, Somnambulist, Incorrigible",
              "Synonyms & Antonyms: Ephemeral, Meticulous, Obsolete, Pragmatic, Ubiquitous, Voracious",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=vocab+root+words+idioms+ssc+cgl+marathon",
            freeReadingUrl: "https://openlibrary.org/search?q=English+Vocabulary",
            pyqFocus: "Correct spelling tests with tricky double consonants (e.g., Accommodation, Millennium, Questionnaire).",
          },
        ],
      },
    ],
    recommendedBooks: [
      { subject: "Quantitative Aptitude", book: "Quantitative Aptitude for Competitive Examinations by R.S. Aggarwal", freeLink: "https://openlibrary.org/search?q=Quantitative+Aptitude" },
      { subject: "English Language", book: "Objective General English by S.P. Bakshi", freeLink: "https://openlibrary.org/search?q=General+English+Grammar" },
      { subject: "General Intelligence", book: "A Modern Approach to Verbal & Non-Verbal Reasoning by R.S. Aggarwal", freeLink: "https://openlibrary.org/search?q=Verbal+Non+Verbal+Reasoning" },
      { subject: "General Knowledge", book: "Lucent's General Knowledge (Science + Static GK)", freeLink: "https://openlibrary.org/search?q=General+Knowledge+Lucent" },
    ],
    syllabus: [
      {
        subject: "Section 1: Mathematical Abilities (Quantitative Aptitude)",
        weight: "30 Questions • 90 Marks (Tier-2)",
        topics: [
          "Number Systems: Computation of Whole Numbers, Decimals, Fractions, Relationships between numbers",
          "Fundamental Arithmetical Operations: Percentages, Ratio and Proportion, Square roots, Averages, Interest (Simple & Compound)",
          "Profit and Loss, Discount, Partnership Business, Mixture and Alligation, Time and distance, Time and work",
          "Algebra: Basic algebraic identities of School Algebra & Elementary surds, Graphs of Linear Equations",
          "Geometry: Familiarity with elementary geometric figures and facts (Triangle centers, Congruence, Similarity, Circle chords/tangents)",
          "Mensuration: Triangle, Quadrilaterals, Regular Polygons, Circle, Right Prism, Cone, Cylinder, Sphere, Hemispheres",
          "Trigonometry: Trigonometric ratios, Degree and Radian Measures, Standard Identities, Heights and Distances",
          "Statistics and Probability: Calculation of mean, median, mode, standard deviation, calculation of simple probabilities",
        ],
      },
      {
        subject: "Section 2: Reasoning and General Intelligence",
        weight: "30 Questions • 90 Marks (Tier-2)",
        topics: [
          "Semantic Analogy, Symbolic/Number Analogy, Figural Analogy",
          "Semantic Classification, Symbolic/Number Classification, Figural Classification",
          "Semantic Series, Number Series, Figural Series, Problem Solving, Word Building",
          "Coding & de-coding, Numerical Operations, Symbolic Operations, Trends, Space Orientation",
          "Venn Diagrams, Drawing inferences, Punched hole/pattern-folding & unfolding",
          "Figural Pattern-folding and completion, Indexing, Address matching, Date & city matching",
          "Classification of centre codes/roll numbers, Small & Capital letters/numbers coding",
          "Critical thinking, Emotional Intelligence, Social Intelligence",
        ],
      },
      {
        subject: "Section 3: English Language and Comprehension",
        weight: "45 Questions • 135 Marks (Tier-2)",
        topics: [
          "Vocabulary: Synonyms, Antonyms, Homonyms, Spelling/detecting mis-spelt words",
          "Idioms & Phrases, One word substitution, Improvement of Sentences",
          "Grammar: Active/Passive Voice of Verbs, Conversion into Direct/Indirect narration",
          "Shuffling of Sentence parts, Shuffling of Sentences in a passage",
          "Cloze Passage & Reading Comprehension passages (Factual & Analytical stories)",
        ],
      },
      {
        subject: "Section 4: General Awareness & Science",
        weight: "25 Questions • 75 Marks (Tier-2)",
        topics: [
          "History: Indus Valley, Maurya/Gupta, Delhi Sultanate, Mughals, Freedom Movement 1857-1947",
          "Culture: Classical & Folk Dances, Music, Festivals, Paintings, UNESCO Heritage sites",
          "Geography: Physical features of India, Rivers & Tributaries, Mountains, Climate, Soil, Minerals",
          "Economic Scene: National Income, Inflation, Banking System (RBI Monetary Policy), Five Year Plans",
          "General Policy & Scientific Research: Fundamental Rights/Duties, President, Parliament, Panchayats",
          "General Science: Physics laws & units, Everyday Chemistry compounds, Human Anatomy & Vitamins",
          "Current Events: National/International Awards, Sports, Summits, Defense Exercises, Appointments",
        ],
      },
      {
        subject: "Section 5: Computer Knowledge Module (Qualifying)",
        weight: "20 Questions • 60 Marks",
        topics: [
          "Computer Basics: Organization of a computer, CPU, Input/Output devices, Computer memory, Memory organization, Back-up devices, Ports, Windows Explorer, Keyboard shortcuts",
          "Software: Windows Operating System including basics of Microsoft Office (MS Word, MS Excel and Power Point etc.)",
          "Working with Internet and e-mails: Web Browsing & Searching, Downloading & Uploading, Managing an E-mail Account, e-Banking",
          "Basics of networking and cyber security: Networking devices and protocols, Network & information security threats (like hacking, virus, worms, Trojans etc.) and preventive measures",
        ],
      },
    ],
  },

  {
    id: "banking-exams",
    name: "Banking Exams (IBPS PO/Clerk, SBI PO/Clerk, RBI Grade B)",
    shortName: "Banking & Insurance",
    badge: "🏦 Banking & Financial Services",
    icon: "🏦",
    accentColor: "#3b82f6",
    tagline: "Probationary Officer & Specialist Cadre in Public Sector Banks and Reserve Bank of India",
    eligibility: "Bachelor's Degree • Age 20-30 years",
    totalMarks: "Prelims (100 Marks) + Mains (200 Marks) + Interview (100 Marks)",
    phases: [
      {
        phaseName: "Phase 1: Speed Arithmetic & Core Logic (Weeks 1-5)",
        focus: "Calculation speed, Vedic Math & Fundamental Puzzles",
        milestones: [
          "Simplification & Approximation (Target 15 questions in 5 minutes)",
          "Quadratic Equations & Missing/Wrong Number Series",
          "Data Interpretation: Tabular, Bar Graph, Line Graph, Pie Chart, Caselet DI",
          "Reasoning: Seating Arrangement (Circular, Linear, Square, Floor-based puzzles)",
        ],
      },
      {
        phaseName: "Phase 2: High-Level Reasoning & Banking Awareness (Weeks 6-10)",
        focus: "Mains-level Puzzles, Critical Reasoning & Financial Literacy",
        milestones: [
          "Complex Puzzles: Multi-variable blood relations, scheduling, uncertain number puzzles",
          "Critical Reasoning: Statement-Assumption, Cause & Effect, Course of Action, Inference",
          "Banking Awareness: RBI Monetary Policy instruments (Repo, Reverse Repo, CRR, SLR), Basel Norms, NPA Resolution (IBC, SARFAESI)",
          "Financial Terms: Capital Market vs Money Market, Digital Banking, UPI, CBDC, Priority Sector Lending",
        ],
      },
      {
        phaseName: "Phase 3: English Reading Speed & Descriptive Writing (Weeks 11-14)",
        focus: "Long RCs, Error Spotting, Letter Writing & Essay Practice",
        milestones: [
          "Daily 2 Financial/Economic Reading Comprehension passages (The Economist / LiveMint)",
          "Grammar precision: Subject-Verb Agreement, Parallelism, Connectors, Para-jumbles",
          "Descriptive Paper: Practice typing formal/informal banking letters & 250-word financial essays",
        ],
      },
      {
        phaseName: "Phase 4: Speed Mocks & Sectional Pressure Tests (Weeks 15-18)",
        focus: "Timed 60-minute Prelims Mocks + 3-hour Mains Full Tests",
        milestones: [
          "Daily 2 full Prelims mock tests (Target 75+ score with 90%+ accuracy)",
          "Weekly 2 full-length Mains mock tests with descriptive typing submission",
          "Current Affairs Revision: Past 6 months Banking, Appointments, MoU, RBI circulars",
        ],
      },
    ],
    chapterGuides: [
      {
        subjectId: "bank-di-quant",
        subjectName: "Data Interpretation & Quantitative Aptitude",
        icon: "📊",
        weightage: "Prelims: 35 Qs (35 Marks) • Mains: 35 Qs (60 Marks)",
        freeOfficialBooks: [
          {
            name: "Fast Track Objective Arithmetic by Rajesh Verma",
            type: "Open Library Free Access",
            url: "https://openlibrary.org/search?q=Fast+Track+Arithmetic",
            description: "Comprehensive shortcut techniques for speed DI and commercial math.",
          },
          {
            name: "Magical Book on Quicker Maths by M. Tyra",
            type: "Open Library Free Access",
            url: "https://openlibrary.org/search?q=Quicker+Maths+Tyra",
            description: "Vedic math tricks, square roots, cube roots, and calculation accelerators.",
          },
        ],
        freeVideoLectures: [
          {
            title: "Complete Banking Data Interpretation (DI) & Speed Math Course",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=complete+data+interpretation+banking+ibps+sbi+po+marathon",
            description: "High-level Caselets, Missing DIs, Radar graphs, and Arithmetic-based DIs.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "Simplification, Approximation & Number Series",
            importance: "🔥 High Yield (10-15 Marks in Prelims)",
            whatToStudy: "1. Master VBODMAS rule -> 2. Cube roots & Square roots tricks -> 3. Difference and Double-difference series.",
            keyTopics: [
              "VBODMAS Rule: Vinculum, Brackets, Of, Division, Multiplication, Addition, Subtraction",
              "Approximation: Rounding decimals, % calculation shortcuts (e.g. 59.8% of 450 -> 60% of 450 - 0.2%)",
              "Missing Number Series & Wrong Number Series patterns (Prime additions, n²±1, n³±1, alternate patterns)",
              "Quadratic Equations factorization tricks (+ + gives - -, - + gives + +, + - gives - +, - - gives + -)",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=simplification+approximation+quadratic+equations+banking+marathon",
            freeReadingUrl: "https://openlibrary.org/search?q=Quicker+Maths",
            pyqFocus: "Root comparison in quadratic equations without solving full formula.",
          },
          {
            chapterNo: 2,
            title: "Data Interpretation (DI) & Caselet Analysis",
            importance: "🔥 High Yield (Core Mains Focus)",
            whatToStudy: "1. Tabular & Line graphs -> 2. Venn Diagram based Caselets -> 3. Arithmetic DIs (Time & Work DI, SI-CI DI).",
            keyTopics: [
              "Tabular, Bar, Line & Pie Chart Interpretation with high-speed ratio comparisons",
              "Missing DI: Deriving missing values using provided percentage and ratio hints",
              "Caselet DI: Extracting raw textual data into structured tables using Venn diagrams",
              "Radar / Web Charts and Funnel Charts for SBI PO Mains",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=high+level+data+interpretation+sbi+po+mains+marathon",
            freeReadingUrl: "https://openlibrary.org/search?q=Data+Interpretation",
            pyqFocus: "Percentage increase vs Percentage point difference in multi-tier DI.",
          },
        ],
      },
      {
        subjectId: "bank-reasoning",
        subjectName: "Reasoning Ability & High-Level Puzzles",
        icon: "🧩",
        weightage: "Prelims: 35 Qs (35 Marks) • Mains: 45 Qs (60 Marks)",
        freeOfficialBooks: [
          {
            name: "Analytical Reasoning by M.K. Pandey",
            type: "Open Library Free Access",
            url: "https://openlibrary.org/search?q=Analytical+Reasoning+MK+Pandey",
            description: "The foundational book for statement-assumption, course of action, and critical logic.",
          },
        ],
        freeVideoLectures: [
          {
            title: "100 High Level Puzzles & Seating Arrangements for Banking Exams",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=100+puzzles+seating+arrangement+banking+sbi+po+marathon",
            description: "Floor puzzles, Blood relation combinations, Uncertain numbers, and Box arrangements.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "Seating Arrangements & Multi-Variable Puzzles",
            importance: "🔥 High Yield (20-25 Marks in Every Exam)",
            whatToStudy: "1. 2-case elimination method -> 2. Inside/Outside facing circles -> 3. Flat and Floor puzzles with color/fruit variables.",
            keyTopics: [
              "Circular Seating: All facing center vs some facing inside, some facing outside",
              "Linear Seating: Single row parallel rows with persons facing North and South",
              "Floor & Flat Puzzles: 4 floors x 2 flats (Flat A is west of Flat B) with multiple variables",
              "Uncertain Number of Persons in a linear row (deriving total count)",
              "Box Stack Puzzles & Day/Month/Year scheduling with age calculations",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=seating+arrangement+puzzles+banking+masterclass",
            freeReadingUrl: "https://openlibrary.org/search?q=Analytical+Reasoning",
            pyqFocus: "Uncertain number of persons linear puzzle with gap constraints.",
          },
          {
            chapterNo: 2,
            title: "Syllogisms (Only a few), Inequalities & Machine Input-Output",
            importance: "🔥 High Yield",
            whatToStudy: "1. 'Only a few A are B' Venn diagram rules -> 2. Coded inequalities -> 3. Step-by-step Machine Input.",
            keyTopics: [
              "'Only a few A are B' means: (1) Some A are B AND (2) Some A are NOT B",
              "'Only A are B' means: 'All B are A' with B having no relation with any other entity",
              "Coded Inequalities: Direct path vs reverse path (King > Minister > Soldier priorities)",
              "Machine Input-Output: Alphabet alphabetical ordering + Number ascending/descending operations",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=only+a+few+syllogism+machine+input+output+banking+lecture",
            freeReadingUrl: "https://openlibrary.org/search?q=Logical+Reasoning",
            pyqFocus: "Possibility cases in 'Only a few' Syllogism questions.",
          },
        ],
      },
    ],
    recommendedBooks: [
      { subject: "Quantitative Aptitude", book: "Fast Track Objective Arithmetic by Rajesh Verma", freeLink: "https://openlibrary.org/search?q=Fast+Track+Arithmetic" },
      { subject: "Reasoning", book: "Analytical Reasoning by M.K. Pandey", freeLink: "https://openlibrary.org/search?q=Analytical+Reasoning+MK+Pandey" },
      { subject: "Banking Awareness", book: "Banking Awareness by Arihant Experts", freeLink: "https://openlibrary.org/search?q=Banking+Awareness" },
    ],
    syllabus: [
      {
        subject: "Data Analysis and Interpretation (Quantitative Aptitude)",
        weight: "35 Questions • 60 Marks (Mains)",
        topics: [
          "Data Interpretation: Radar/Web charts, Missing DI, Funnel DI, Probability based DI, Arithmetic DI",
          "Data Sufficiency (2 statements & 3 statements)",
          "Quantity 1 and Quantity 2 Comparisons",
          "Advanced Arithmetic: Time & Work (Efficiency & Pipes), Speed Time Distance (Trains & Boats)",
          "Permutations, Combinations & Probability",
        ],
      },
      {
        subject: "Reasoning and Computer Aptitude",
        weight: "45 Questions • 60 Marks (Mains)",
        topics: [
          "Puzzles: Box puzzles, Year calculation puzzles, Matrix puzzles, Flat & Floor puzzles",
          "Machine Input-Output (Shift, Number operations, Step reversal)",
          "Coded Inequalities, Coded Blood Relations, Coded Direction Sense",
          "Logical / Verbal Reasoning: Strong and Weak Arguments, Drawing Conclusions",
          "Binary Logic & Flowchart based reasoning",
        ],
      },
      {
        subject: "General, Economy and Banking Awareness",
        weight: "40 Questions • 40 Marks",
        topics: [
          "Banking in India: History, Nationalization, Structure of Scheduled Commercial Banks",
          "Monetary Policy Committee (MPC) & Central Bank Operations",
          "Banking Technology: RTGS, NEFT, IMPS, NACH, CTS, CBDC, Tokenization",
          "Financial Institutions: SEBI, IRDAI, PFRDA, NABARD, SIDBI, EXIM Bank",
          "Current Financial Affairs: Union Budget, Mergers & Acquisitions, GDP forecasts",
        ],
      },
      {
        subject: "English Language",
        weight: "35 Questions • 40 Marks",
        topics: [
          "Reading Comprehension (Financial, Macro-economic & Socio-technology themes)",
          "Cloze Test, Column Matching (Column 1 & Column 2)",
          "Error Detection & Phrase Replacement",
          "Sentence Rearrangement & Infillers",
        ],
      },
    ],
  },

  {
    id: "state-psc",
    name: "State PSC / Group 1, Group 2 & Group 4 Services",
    shortName: "State PSC / Groups",
    badge: "🗺️ State Civil Services",
    icon: "🗺️",
    accentColor: "#f59e0b",
    tagline: "State Administrative, Police, Revenue, and Commercial Tax Executive Posts (APPSC, TSPSC, UPPSC, BPSC, MPSC, KPSC)",
    eligibility: "Bachelor's Degree • State domicile preference",
    totalMarks: "Prelims (150-300 Marks) + Mains (450-750 Marks)",
    phases: [
      {
        phaseName: "Phase 1: State Specific History & Geography (Months 1-3)",
        focus: "In-depth State History, Culture, Geography & Tribal Heritage",
        milestones: [
          "Study complete State History (Ancient Dynasties, Regional Kingdoms, Freedom Movement in State)",
          "Geography of the State: River basins, soil types, minerals, forests, sanctuary zones, agro-climatic regions",
          "Culture & Heritage: Folk traditions, festivals, regional literature, monuments, architectural legacy",
          "Bifurcation / Formation History and Regional Movements",
        ],
      },
      {
        phaseName: "Phase 2: Indian Polity, Constitution & State Governance (Months 4-6)",
        focus: "Constitutional Machinery, State Administration & Panchayati Raj",
        milestones: [
          "State Executive: Governor, Chief Minister, Council of Ministers, Advocate General",
          "State Legislature: Legislative Assembly, Legislative Council, Legislative Procedures",
          "73rd & 74th Constitutional Amendments: Gram Panchayats, Zilla Parishads, Urban Local Bodies",
          "State Flagship Welfare Schemes (Health, Education, Agriculture, Women Empowerment)",
        ],
      },
      {
        phaseName: "Phase 3: State Economy & Development Programs (Months 7-9)",
        focus: "State Socio-Economic Outlook, Budget & NITI Aayog Indices",
        milestones: [
          "Master the latest State Socio-Economic Survey & Annual Budget",
          "Gross State Domestic Product (GSDP) composition (Agriculture, Industry, Services)",
          "Industrial Corridors, SEZs, Ports, IT hubs, Infrastructure projects",
          "Environment challenges: Water management, drought mitigation, urban pollution",
        ],
      },
      {
        phaseName: "Phase 4: Mains Answer Writing & Mock Test Cycles (Months 10-12)",
        focus: "Descriptive / Objective Full Papers and PYQ Analysis",
        milestones: [
          "Practice State PSC Mains previous years' essay and GS papers",
          "Data & Mental Ability / Logical Reasoning speed practice",
          "Revise 2 rounds of State GK + 1 year National & State Current Affairs",
          "Attempt 20 comprehensive full-length mock examinations",
        ],
      },
    ],
    chapterGuides: [
      {
        subjectId: "state-history-culture",
        subjectName: "State History, Movement & Cultural Heritage",
        icon: "🏛️",
        weightage: "Prelims & Mains: 50-75 Marks",
        freeOfficialBooks: [
          {
            name: "State Official Academy History & Culture Publication",
            type: "State Free University Repository",
            url: "https://openlibrary.org/search?q=State+History+Culture",
            description: "Authentic text for ancient dynasties, medieval sultanates, and regional state reorganization.",
          },
          {
            name: "NCERT Class 12: Themes in Indian History",
            type: "Official NCERT Free PDF",
            url: "https://ncert.nic.in/textbook.php?lehs1=0-4",
            description: "Foundational history and regional temple architecture.",
          },
        ],
        freeVideoLectures: [
          {
            title: "Complete State History & Regional Freedom Movement Marathon",
            channel: "YouTube Open Course",
            url: "https://www.youtube.com/results?search_query=state+psc+history+culture+marathon+full+course",
            description: "Dynasties, literature, peasant revolts, and post-independence reorganization history.",
          },
        ],
        chapters: [
          {
            chapterNo: 1,
            title: "Ancient Dynasties & Architectural Heritage",
            importance: "🔥 High Yield",
            whatToStudy: "1. Inscriptions and coins -> 2. Temple architecture styles (Dravidian/Vesara) -> 3. Royal land grants.",
            keyTopics: [
              "Early ruling dynasties, administrative divisions, capitals, and major inscriptions",
              "Spread of Buddhism and Jainism: Stupas, Chaityas, Viharas, and rock-cut cave architecture",
              "Sanskrit and vernacular literature patronized by ancient kings",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=ancient+state+history+dynasties+psc+lecture",
            freeReadingUrl: "https://ncert.nic.in/textbook.php?lehs1=1-4",
            pyqFocus: "Key temple architecture patrons and famous rock inscriptions.",
          },
          {
            chapterNo: 2,
            title: "State Peasant Movements, Freedom Struggle & Reorganization",
            importance: "🔥 High Yield",
            whatToStudy: "1. Land tenure systems (Zamindari/Ryotwari) -> 2. Tribal uprisings against British/Feudal lords -> 3. Linguistic reorganization.",
            keyTopics: [
              "Impact of British colonial revenue policies on regional agriculture and weavers",
              "Armed peasant rebellions, tribal revolts, and social reform leaders",
              "Role of state leaders in Non-Cooperation, Civil Disobedience, and Quit India Movements",
              "Fazal Ali Commission (States Reorganisation Act 1956) and linguistic state formation milestones",
            ],
            freeVideoUrl: "https://www.youtube.com/results?search_query=state+reorganization+freedom+struggle+psc+lecture",
            freeReadingUrl: "https://openlibrary.org/search?q=State+History",
            pyqFocus: "Linguistic reorganization committees (Dhar Commission, JVP Committee, States Reorganisation Commission).",
          },
        ],
      },
    ],
    recommendedBooks: [
      { subject: "State History & Culture", book: "Comprehensive History of the State (State Official Academy)", freeLink: "https://openlibrary.org/search?q=State+History" },
      { subject: "Indian Polity", book: "Indian Polity by M. Laxmikanth", freeLink: "https://openlibrary.org/search?q=Indian+Polity+Laxmikanth" },
      { subject: "Economy", book: "State Socio-Economic Survey & Annual Budget Document", freeLink: "https://openlibrary.org/search?q=Indian+Economy" },
      { subject: "Mental Ability", book: "Quantitative Aptitude & Logical Reasoning by R.S. Aggarwal", freeLink: "https://openlibrary.org/search?q=Logical+Reasoning" },
    ],
    syllabus: [
      {
        subject: "Paper 1: General Studies & Mental Ability",
        weight: "150 Marks",
        topics: [
          "Current events of regional, national and international importance",
          "General Science — contemporary developments in Science and Technology and their implications",
          "History of India with emphasis on Indian National Movement",
          "World Geography, Physical, Social and Economic Geography of India with focus on the State",
          "Indian Polity and Governance: Constitution, Political System, Panchayati Raj, Public Policy",
          "Economic development in India since Independence and sustainable development",
          "Disaster management: vulnerability profile, prevention and mitigation strategies",
          "Logical reasoning, analytical ability and data interpretation",
          "Basic Data Analysis (Tabulation of data, Visual representation, Basic Statistics)",
        ],
      },
      {
        subject: "Paper 2: History, Culture & Heritage of the State",
        weight: "150 Marks",
        topics: [
          "Social and Cultural History of the State (Early kingdoms, religious movements, art and architecture)",
          "Medieval society, Bhakti movement, regional literature and architectural evolution",
          "Advent of Europeans, Trade, East India Company rule, impact on regional agrarian economy",
          "Origin and growth of Nationalist Movement in the State (1857 to 1947)",
          "Post-independence state reorganization, regional movements, integration & socio-political landmarks",
          "Tribal and peasant revolts in the state, social reform leaders and cultural revival",
        ],
      },
      {
        subject: "Paper 3: Indian Economy & State Socio-Economic Development",
        weight: "150 Marks",
        topics: [
          "Structure of Indian Economy, Economic Planning, NITI Aayog, National Income computation",
          "State Economy: Sectoral growth (Agriculture, Industry, Infrastructure, Services)",
          "State Financial Resources: Revenue receipts, tax devolution, fiscal deficit, debt sustainability",
          "Major State Welfare Schemes: Direct Benefit Transfer (DBT), Housing, Healthcare, Rural Employment",
          "Human Resource Development: Literacy rates, demographic dividend, healthcare indices",
          "Natural Resources, Environmental degradation, climate change mitigation, sustainable agriculture",
        ],
      },
    ],
  },
];
